### ISSUE TITLE
Skip unity tests using `System.Text.Json`

### ISSUE THREAD

**Issue by greymistcube** [planetarium/libplanet#2448] opened 2022-10-22 02:49 UTC
https://github.com/planetarium/libplanet/blob/d998e4bcf52d98ba0f3b837cd0ea82d6bc026491/Libplanet.Tests/TestUtils.cs#L576-L579

As seen in the comment above, there's an issue with [Unity] not playing nice with `System.Text.Json`. Above implementation is an attempt to skip tests under mono build, but for whatever reason does not seem to work properly. I haven't had the time to look into it any further, but my first guess would be `Xunit.SkipException` being thrown no directly under the testing method. We need to bypass this in some other way.

[Unity]: https://unity.com/

**Comment by dahlia** [comment] 2022-10-23 09:36
Probably duplicate of #2330.

**Comment by tkiapril** [comment] 2022-10-24 02:38
AFAIK to skip a test with SkipException the test fact has to be marked with `[SkippableFact]`. Currently Libplanet.Tests.Action.Sys.MintTest.JsonSerialization is failing, and it's marked with `[Fact]` instead of `[SkippableFact]`, so it's likely this is the culprit.

**Closed** 2022-10-27 06:29 UTC
Labels: ci & cd
